# Generated by Django 4.0.7 on 2023-11-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0007_spec_approved_dt_spec_sunset_extended_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuser',
            name='descr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
