# Generated by Django 4.0.7 on 2023-11-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0008_roleuser_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
    ]
