# Generated by Django 4.0.7 on 2023-11-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='spec.location'),
        ),
    ]
